"""FastAPI request/response Pydantic models, split by domain."""

from __future__ import annotations

from eagle_rag.api.schemas.attachments import (
    AttachmentOut,
    AttachmentUploadResponse,
)
from eagle_rag.api.schemas.common import DeletedResponse, OkResponse, RootResponse
from eagle_rag.api.schemas.documents import DocumentListResponse, DocumentOut, ImageMetaOut
from eagle_rag.api.schemas.health import (
    AdminCeleryResponse,
    AdminConfigOut,
    AdminKnowhereResponse,
    AdminMcpResponse,
    AdminMilvusResponse,
    AdminPixelragResponse,
    AdminProbesResponse,
    AdminVlmResponse,
    DependencyStatus,
    DependencySummary,
    HealthResponse,
    McpToolDefinition,
    McpToolsResponse,
    ProbeDetail,
)
from eagle_rag.api.schemas.ingest import (
    IngestResponse,
    TaskAuditOut,
    TaskListResponse,
    TaskLogEntry,
    TaskLogsResponse,
    TaskRetryResponse,
)
from eagle_rag.api.schemas.knowledge_bases import (
    FormatDistributionSegment,
    IngestionVolumePoint,
    KBCollectionsResponse,
    KBCollectionStats,
    KBCreate,
    KBDeleteResponse,
    KBDetailOut,
    KBFacetsResponse,
    KBFormatDistributionResponse,
    KBIngestionVolumeResponse,
    KBItem,
    KBListResponse,
    KBOverviewResponse,
    KBUpdate,
    RebuildResponse,
)
from eagle_rag.api.schemas.notifications import (
    NotificationListResponse,
    NotificationOut,
    NotificationReadAllResponse,
    NotificationReadResponse,
)
from eagle_rag.api.schemas.query import (
    ImageSource,
    QueryFilters,
    QueryRequest,
    QueryResponse,
    QuerySources,
    QueryStep,
    RouteInfo,
    TextSource,
)
from eagle_rag.api.schemas.sessions import (
    MessageListResponse,
    MessageOut,
    SessionCreate,
    SessionListResponse,
    SessionSummary,
)
from eagle_rag.api.schemas.users import (
    PreferencesUpdate,
    UserOut,
    UserPreferences,
    UserUpdate,
)

__all__ = [
    "DeletedResponse",
    "OkResponse",
    "RootResponse",
    "DocumentOut",
    "DocumentListResponse",
    "ImageMetaOut",
    "IngestResponse",
    "TaskAuditOut",
    "TaskLogEntry",
    "TaskListResponse",
    "TaskLogsResponse",
    "TaskRetryResponse",
    "DependencyStatus",
    "DependencySummary",
    "ProbeDetail",
    "HealthResponse",
    "McpToolDefinition",
    "McpToolsResponse",
    "AdminCeleryResponse",
    "AdminMilvusResponse",
    "AdminPixelragResponse",
    "AdminKnowhereResponse",
    "AdminVlmResponse",
    "AdminMcpResponse",
    "AdminConfigOut",
    "AdminProbesResponse",
    "KBCreate",
    "KBUpdate",
    "KBItem",
    "KBListResponse",
    "KBDetailOut",
    "KBDeleteResponse",
    "RebuildResponse",
    "KBOverviewResponse",
    "KBFormatDistributionResponse",
    "FormatDistributionSegment",
    "KBIngestionVolumeResponse",
    "IngestionVolumePoint",
    "KBCollectionsResponse",
    "KBCollectionStats",
    "KBFacetsResponse",
    "QueryFilters",
    "QueryRequest",
    "TextSource",
    "ImageSource",
    "QuerySources",
    "RouteInfo",
    "QueryStep",
    "QueryResponse",
    "SessionCreate",
    "SessionSummary",
    "SessionListResponse",
    "MessageOut",
    "MessageListResponse",
    "UserOut",
    "UserUpdate",
    "UserPreferences",
    "PreferencesUpdate",
    "NotificationOut",
    "NotificationListResponse",
    "NotificationReadResponse",
    "NotificationReadAllResponse",
    "AttachmentOut",
    "AttachmentUploadResponse",
]
